-- Insert test data for briefs
INSERT INTO public.briefs (
  empresa, contacto, cargo, telefono, correo, ubicacion, horario, sitio_web,
  instagram, facebook, tiktok,
  que_hace, desde_cuando, problema_resuelve, tipo_clientes,
  propuesta_valor, diferenciador_1, diferenciador_2, diferenciador_3, resultado_promesa,
  mas_confianza, objeciones, pruebas, pruebas_detalle,
  productos, combos, promociones,
  producto_estrella, porque_mas_vendido, mas_conviene, objetivo_mes,
  objetivos_redes, objetivo_uno, meta_concreta,
  edad_cliente, genero_cliente, ubicacion_cliente, nivel_economico, trabajo_estilo_vida,
  problema_cliente, cliente_valora, miedos_dudas, cliente_pasa_tiempo, frase_tipica,
  competidor_1, competidor_2, competidor_3, que_gusta_competencia, que_mal_competencia, cuentas_inspiran,
  tono_marca, colores_marca, tipografias, logo_png, tono_prohibido,
  tiene_fotos_videos, tiene_grabador, tiene_testimonios, tiene_catalogo, drive_link,
  invertir_pauta, presupuesto_mensual, producto_pautar
) VALUES (
  'Café Don Pepe', 'María González', 'Gerente General', '+504 9876-5432', 'maria@cafedonpepe.hn',
  'Tegucigalpa, Honduras', 'Lunes a Sábado 7am - 6pm', 'https://cafedonpepe.hn',
  'https://instagram.com/cafedonpepe', 'https://facebook.com/cafedonpepe', 'https://tiktok.com/@cafedonpepe',
  'Somos una cafetería artesanal que ofrece café de origen hondureño y pasteles caseros.',
  'Desde 2018', 
  'Café de calidad premium a precios accesibles en un ambiente acogedor.',
  ARRAY['Personas', 'Empresas'],
  'El mejor café de Copán servido con amor hondureño.',
  'Café 100% de origen Copán', 
  'Ambiente acogedor con WiFi gratis',
  'Pasteles caseros diarios',
  'Empezarás tu día con energía y buen sabor.',
  '6 años de experiencia, 500+ reseñas 5 estrellas.',
  'Está caro, lo voy a pensar',
  ARRAY['Testimonios', 'Reseñas'],
  '523 reseñas en Google con 4.9 estrellas.',
  '[{"nombre": "Café Americano", "precio": "L. 45", "costo": "L. 12", "ganancia": "L. 33"}, {"nombre": "Cappuccino", "precio": "L. 65", "costo": "L. 18", "ganancia": "L. 47"}]'::jsonb,
  'Combo Desayuno: Café + Desayuno Típico por L. 150',
  '2x1 en Cappuccino los martes',
  'Cappuccino con arte latte', 
  'Mejor margen y muy instagrameable.',
  'Combo Desayuno Ejecutivo',
  'Aumentar ventas del Combo en 30%',
  ARRAY['Más mensajes por WhatsApp', 'Más visitas al negocio'],
  'Más visitas al negocio',
  '100 clientes nuevos al mes',
  '25-45 años', 'Ambos', 'Tegucigalpa', 'medio',
  'Profesionales jóvenes, emprendedores',
  'Encontrar un lugar tranquilo con buen WiFi',
  ARRAY['Calidad', 'Atención'],
  'Dudan si el café será bueno',
  ARRAY['Instagram', 'WhatsApp'],
  'Quiero un lugar tranquilo con buen café',
  'Espresso Americano', 'Coffee Shop Santa Lucía', 'Típicos Coffee',
  'Me gusta el diseño moderno',
  'Servicio lento a veces',
  '@bluebottlecoffee',
  ARRAY['Cercana y barrio'],
  'Marrón café, beige, verde bosque',
  'Playfair Display, Open Sans',
  'si',
  'Evitar ser formales',
  'si', 'si', 'no', 'si', 'https://drive.google.com/ejemplo',
  'si', 'L. 5,000', 'Combo Desayuno Ejecutivo'
);